version: "3"
services:
  client:
    image: client
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_SERVER_URL=http://localhost:5000
    networks:
      - url-shortener-app
  server:
    image: server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=local
      - DB_HOST=host.docker.internal
      - DB_PORT=27017
    depends_on:
      - mongo
    networks:
      - url-shortener-app
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - url-shortener-app
networks:
  url-shortener-app:
    driver: bridge
volumes:
  data-volume:
    driver: local
